name: Version Build
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: write # Necessary to write to the repository
  packages: write
on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'GuillaumeFalourd'
        repository: 'poc-github-actions'
    - name: connect to repo
      uses: actions/checkout@v3
      with:
        repository: 'badal-github-sandbox/duplicate-public-repo'
        token: ${{secrets.PAT}}
    - name: push to repository 
      run: |
        echo "ROOT"
        ls -la
        echo "CLONED REPO"
        cd poc-github-actions
        rm -fr .git
        ls -la
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git remote remove origin
        git remote add origin https://x-access-token:${{ secrets.PAT }}@github.com/badal-github-sandbox/poc-github-actions
        git remote -v
        git checkout "${GITHUB_REF:11}"
        git add .
        git commit -m "Automated push"
        git branch -M main
        git push origin main --force