name: Version Build

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Commit and push if content changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'arjun-nair-telus'
        repository: 'poc-github-actions'
    - name: Access cloned repository content
      run: |
        echo "ROOT"
        ls -la
        echo "CLONED REPO"
        cd poc-github-actions
        ls -la  