name: Version Build

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'GuillaumeFalourd'
        repository: 'poc-github-actions'
    - name: Access cloned repository content
      run: |
        echo "ROOT"
        ls -la
        echo "CLONED REPO"
        cd poc-github-actions
        ls -la  
        rm -fr .git
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/badal-github-sandbox/poc-github-actions
        git checkout "${GITHUB_REF:11}"
        git add -A
        git commit -m "Automated push"
        git push origin master